[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chatybot"
version = "0.4.1"
description = "A CLI-based AI chat assistant"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE.md" }
authors = [{ name = "Jon Allen" }]
dependencies = [
    "openai>=1.61.0",
    "tinydb",
    "pygments",
    "parsley",
    "aiohttp"
]

[project.scripts]
chatybot = "chatybot.main:run"
chatdsl_parse = "chatybot.chatdsl_parse:main"

[tool.setuptools.package-data]
chatybot = ["*.toml", "*.chatdsl"]
