#!/usr/bin/env python3
"""
dispatcher.py - Centralized tool execution gateway for ChatyBot.
Parses tool invocations generated by ChatDSL and maps them to validated local tools.
"""

import os
import sys
import json
import importlib
import argparse
from typing import Any, Dict, Tuple

# Add the directory containing dispatcher.py to the path so that chatybot modules can be imported
dispatcher_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(dispatcher_dir)
src_dir = os.path.join(project_root, "src")
if src_dir not in sys.path:
    sys.path.insert(0, src_dir)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Attempt safe database hooks if integrated into the runtime
try:
    from chatybot import chatydb
except ImportError:
    chatydb = None

try:
    import tomllib
except ImportError:
    # Python < 3.11 fallback
    try:
        import tomli as tomllib
    except ImportError:
        tomllib = None

DEFAULT_CONFIG_PATH = os.path.expanduser("~/.config/chatybot/tools_config.toml")
if not os.path.exists(DEFAULT_CONFIG_PATH):
    DEFAULT_CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools_config.toml")


def load_configs(config_path: str) -> Dict[str, Any]:
    """Loads and returns the TOML tool definitions configuration."""
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Configuration file missing: {config_path}")

    if tomllib:
        with open(config_path, "rb") as f:
            return tomllib.load(f)
    else:
        # Try with toml package for older Python versions
        try:
            import toml
            with open(config_path, "r", encoding="utf-8") as f:
                return toml.load(f)
        except ImportError:
            raise RuntimeError("The 'toml' package is required to parse tool definitions. Install with 'pip install toml'.")


def write_json_response(data: Dict[str, Any], status_code: int = 0):
    """Prints a consistent JSON string to stdout and terminates."""
    print(json.dumps(data, indent=2))
    sys.exit(status_code)


def validate_and_route(invocation: Dict[str, Any], config: Dict[str, Any]) -> Tuple[Any, list, dict]:
    """Validates the invocation against config rules and prepares dynamic routing execution."""
    tool_name = invocation.get("tool")
    args = invocation.get("arguments", {})

    if not tool_name:
        raise ValueError("Invalid invocation block: 'tool' field missing.")

    tools_registry = config.get("tools", {})
    if tool_name not in tools_registry:
        raise KeyError(f"The tool '{tool_name}' is not registered in the system.")

    tool_meta = tools_registry[tool_name]
    if not tool_meta.get("enabled", False):
        raise PermissionError(f"Access Denied: Tool '{tool_name}' is currently disabled in configuration.")

    # Parameter Verification
    declared_params = tool_meta.get("parameters", {})
    for param_name, param_rules in declared_params.items():
        is_optional = param_rules.get("optional", False)
        if param_name not in args:
            if not is_optional:
                raise KeyError(f"Missing required argument: '{param_name}' for tool '{tool_name}'.")
            continue

        # Simple type checking runtime enforcement
        expected_type = param_rules.get("type")
        val = args[param_name]
        if expected_type == "string" and not isinstance(val, str):
            raise TypeError(f"Argument '{param_name}' must be a string.")
        elif expected_type == "number" and not isinstance(val, (int, float)):
            raise TypeError(f"Argument '{param_name}' must be a number.")
        elif expected_type == "boolean" and not isinstance(val, bool):
            raise TypeError(f"Argument '{param_name}' must be a boolean.")
        elif expected_type == "array" and not isinstance(val, list):
            raise TypeError(f"Argument '{param_name}' must be an array/list.")

    # Dynamically resolve target module and function
    module_path = tool_meta.get("module")
    func_name = tool_meta.get("function")

    if not module_path or not func_name:
        raise ImportError(f"Improperly configured system backing metadata for '{tool_name}'.")

    try:
        mod = importlib.import_module(module_path)
        func = getattr(mod, func_name)
    except (ImportError, AttributeError) as e:
        raise ImportError(f"Failed to import tool '{tool_name}': {str(e)}")

    if tool_name == "run_command":
        shell_config = config.get("config", {}).get("shell", True)
        if isinstance(shell_config, str):
            shell_config = shell_config.lower() in ("true", "1", "yes", "on")
        args["shell"] = bool(shell_config)

    return func, [], args


def log_to_database(tool_name: str, args: dict, status: str):
    """Safely records execution metadata into TinyDB session histories if available."""
    if chatydb and hasattr(chatydb, "log_tool_execution"):
        try:
            chatydb.log_tool_execution(tool_name, args, status)
        except Exception as db_err:
            sys.stderr.write(f"Database logging warning: {db_err}\n")


def main():
    parser = argparse.ArgumentParser(description="ChatyBot Core Local Tool Dispatcher Runtime Gateway.")
    parser.add_argument("invocation_file", help="Path to the JSON payload generated via ChatDSL.")
    parser.add_argument("--config", default=DEFAULT_CONFIG_PATH, help="Path override for tools_config.toml.")
    args = parser.parse_args()

    # 1. Parse Invocation Payload
    if not os.path.exists(args.invocation_file):
        write_json_response({
            "status": "error",
            "message": f"Invocation source target not found: {args.invocation_file}",
            "code": "INVOCATION_FILE_MISSING"
        }, status_code=1)

    try:
        with open(args.invocation_file, "r", encoding="utf-8") as f:
            invocation_data = json.load(f)
    except Exception as exc:
        write_json_response({
            "status": "error",
            "message": f"Malformed payload JSON structure: {str(exc)}",
            "code": "INVALID_JSON"
        }, status_code=1)

    # 2. Load and Validate Configuration
    try:
        config_data = load_configs(args.config)
        executable_target, target_args, target_kwargs = validate_and_route(invocation_data, config_data)
    except Exception as err:
        tool_attempt = invocation_data.get("tool", "unknown")
        log_to_database(tool_attempt, invocation_data.get("arguments", {}), "rejected")
        write_json_response({
            "status": "error",
            "tool": tool_attempt,
            "message": str(err),
            "code": "VALIDATION_FAILURE"
        }, status_code=1)

    # 3. Execute Target Module Function Safely
    try:
        execution_result = executable_target(*target_args, **target_kwargs)
        log_to_database(invocation_data["tool"], target_kwargs, "success")
        write_json_response({
            "status": "success",
            "tool": invocation_data["tool"],
            "result": execution_result
        }, status_code=0)
    except Exception as runtime_exc:
        log_to_database(invocation_data["tool"], target_kwargs, "failed")
        write_json_response({
            "status": "error",
            "tool": invocation_data["tool"],
            "message": f"Runtime execution exception triggered: {str(runtime_exc)}",
            "code": "TOOL_RUNTIME_ERROR"
        }, status_code=1)


if __name__ == "__main__":
    main()
